### ISSUE TITLE
how to run?

### ISSUE THREAD

**Issue by spyshow** [dupontgu/qr-file-share#1]
hi 

nice idea but how to run it? 
i installed the required packages but when i open the index.html it gave me "Workin on it..."

**Comment by dupontgu** [comment]
Hey! Sorry, I forgot to finish that part.

If you're running the python script, and you've installed the dependencies (with `pip install -r requirements.txt`), you should be able to just run `python generate_pr.py example_file.png`. It will create a new file called `example_file.png_qr.png` in this case.

I also made a simple browser based UI which you can either use online (if it doesn't matter) or download to your computer as a local webpage. It's now hosted [on github pages](https://dupontgu.github.io/qr-file-share/)
